version: "3.5"
networks:
  api_server_default:
    external: 
      name: api_network
services:
  paymentapp:
    networks:
      - api_server_default
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV_NAME: prod
    ports:
      - 9100:9100